"""dropped projects table, added message evaluations and
updated references.

Revision ID: 067c5d3f70b8
Revises: f073f758f338
Create Date: 2025-10-15 10:42:35.525492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '067c5d3f70b8'
down_revision: Union[str, Sequence[str], None] = 'f073f758f338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guidelines',
    sa.Column('guideline_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('breach_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('guideline_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('moderator_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('breach_type', sa.String(), nullable=False),
    sa.Column('breach_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('moderator_deployments',
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('moderator_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['moderator_id'], ['moderators.moderator_id'], ),
    sa.PrimaryKeyConstraint('deployment_id')
    )
    op.drop_table('projects')
    op.add_column('moderators', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('moderators', sa.Column('guideline_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'moderators', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'moderators', 'guidelines', ['guideline_id'], ['guideline_id'])
    op.drop_column('moderators', 'state')
    op.drop_column('moderators', 'platform')
    op.drop_column('moderators', 'deployed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderators', sa.Column('deployed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('moderators', sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('moderators', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'moderators', type_='foreignkey')
    op.drop_constraint(None, 'moderators', type_='foreignkey')
    op.drop_column('moderators', 'guideline_id')
    op.drop_column('moderators', 'user_id')
    op.create_table('projects',
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('guidelines', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('topics', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('project_id', name=op.f('projects_pkey'))
    )
    op.drop_table('moderator_deployments')
    op.drop_table('messages')
    op.drop_table('guidelines')
    # ### end Alembic commands ###
