"""added fields to users table

Revision ID: 39e74d2d783b
Revises: d6f6183fa3bc
Create Date: 2025-10-25 15:04:35.633112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39e74d2d783b'
down_revision: Union[str, Sequence[str], None] = 'd6f6183fa3bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('users', sa.Column('pricing_tier', sa.String(), nullable=False))
    op.add_column('users', sa.Column('payment_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'payment_info')
    op.drop_column('users', 'pricing_tier')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###
