"""x

Revision ID: 915ea6348c3b
Revises: 067c5d3f70b8
Create Date: 2025-10-15 19:54:39.070978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '915ea6348c3b'
down_revision: Union[str, Sequence[str], None] = '067c5d3f70b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guidelines', sa.Column('name', sa.String(), nullable=False))
    op.add_column('guidelines', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guidelines', 'created_at')
    op.drop_column('guidelines', 'name')
    # ### end Alembic commands ###
