FROM python:3.12-slim-trixie

RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates

ADD https://astral.sh/uv/install.sh /uv-installer.sh

RUN sh /uv-installer.sh && rm /uv-installer.sh

ENV PATH="/root/.local/bin/:$PATH"

RUN echo $PATH

ADD . /app

WORKDIR /app

RUN uv sync --locked

RUN uv run alembic upgrade head

CMD ["uv", "run", "src/main.py"]