"""Created tables

Revision ID: 1123e977976e
Revises: 
Create Date: 2026-01-16 19:21:58.272059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1123e977976e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('jwt', sa.String(), nullable=True),
    sa.Column('discord_oauth_payload', sa.String(), nullable=True),
    sa.Column('pricing_tier', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('moderators',
    sa.Column('moderator_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('platform_server_id', sa.String(), nullable=False),
    sa.Column('conf', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('moderator_id')
    )
    op.create_table('action_events',
    sa.Column('action_id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('moderator_id', sa.UUID(), nullable=False),
    sa.Column('platform_user_id', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('action_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['moderator_id'], ['moderators.moderator_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_index(op.f('ix_action_events_action_type'), 'action_events', ['action_type'], unique=False)
    op.create_table('evaluation_events',
    sa.Column('event_id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('moderator_id', sa.UUID(), nullable=False),
    sa.Column('platform_user_id', sa.String(), nullable=False),
    sa.Column('severity_score', sa.Float(), nullable=False),
    sa.Column('behaviour_score', sa.Float(), server_default=sa.text('0.00'), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['moderator_id'], ['moderators.moderator_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation_events')
    op.drop_index(op.f('ix_action_events_action_type'), table_name='action_events')
    op.drop_table('action_events')
    op.drop_table('moderators')
    op.drop_table('users')
    # ### end Alembic commands ###
