"""removed violation_detected and confidence_score from message-evaluations

Revision ID: 189b52d7c0c5
Revises: 2ed6c30ba3a5
Create Date: 2025-11-02 11:19:42.251109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '189b52d7c0c5'
down_revision: Union[str, Sequence[str], None] = '2ed6c30ba3a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_evaluations', sa.Column('moderator_id', sa.UUID(), nullable=False))
    op.drop_column('message_evaluations', 'violation_detected')
    op.drop_column('message_evaluations', 'confidence_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_evaluations', sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('message_evaluations', sa.Column('violation_detected', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('message_evaluations', 'moderator_id')
    # ### end Alembic commands ###
