"""Converting pricing_tier from int to str in users

Revision ID: 18b225b423ce
Revises: ffef9c434519
Create Date: 2026-01-18 16:39:45.652627

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "18b225b423ce"
down_revision: Union[str, Sequence[str], None] = "ffef9c434519"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users ADD COLUMN pricing_tier_new VARCHAR")
    op.execute(
        """
        UPDATE users
        SET pricing_tier_new = CASE pricing_tier
            WHEN 0 THEN 'free'
            WHEN 1 THEN 'pro'
        END
        """
    )
    op.execute("ALTER TABLE users DROP COLUMN pricing_tier;")
    op.execute("ALTER TABLE users RENAME COLUMN pricing_tier_new TO pricing_tier;")

    # # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "pricing_tier",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
