"""added status field to moderators

Revision ID: 2c099994dd30
Revises: 74b228c3ef45
Create Date: 2025-11-01 14:25:19.949668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c099994dd30'
down_revision: Union[str, Sequence[str], None] = '74b228c3ef45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderators', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moderators', 'status')
    # ### end Alembic commands ###
