"""dropped deployments table and added fields to moderators table

Revision ID: 2ed6c30ba3a5
Revises: 7f19894fb751
Create Date: 2025-11-01 18:56:41.187360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ed6c30ba3a5'
down_revision: Union[str, Sequence[str], None] = '7f19894fb751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderator_event_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('moderator_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('action_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_status', sa.String(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['moderator_id'], ['moderators.moderator_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_moderator_event_logs_created_at'), 'moderator_event_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_moderator_event_logs_event_type'), 'moderator_event_logs', ['event_type'], unique=False)
    op.drop_table('moderator_deployments')
    op.drop_index(op.f('ix_moderator_deployment_event_logs_created_at'), table_name='moderator_deployment_event_logs')
    op.drop_index(op.f('ix_moderator_deployment_event_logs_event_type'), table_name='moderator_deployment_event_logs')
    op.drop_table('moderator_deployment_event_logs')
    op.drop_column('messages', 'deployment_id')
    op.add_column('moderators', sa.Column('platform', sa.String(), nullable=False))
    op.add_column('moderators', sa.Column('platform_server_id', sa.String(), nullable=False))
    op.add_column('moderators', sa.Column('conf', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moderators', 'conf')
    op.drop_column('moderators', 'platform_server_id')
    op.drop_column('moderators', 'platform')
    op.add_column('messages', sa.Column('deployment_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_table('moderator_deployment_event_logs',
    sa.Column('log_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('moderator_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('deployment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('action_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action_params', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('action_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stack_trace', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['moderator_deployments.deployment_id'], name=op.f('moderator_deployment_event_logs_deployment_id_fkey')),
    sa.ForeignKeyConstraint(['moderator_id'], ['moderators.moderator_id'], name=op.f('moderator_deployment_event_logs_moderator_id_fkey')),
    sa.PrimaryKeyConstraint('log_id', name=op.f('moderator_deployment_event_logs_pkey'))
    )
    op.create_index(op.f('ix_moderator_deployment_event_logs_event_type'), 'moderator_deployment_event_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_moderator_deployment_event_logs_created_at'), 'moderator_deployment_event_logs', ['created_at'], unique=False)
    op.create_table('moderator_deployments',
    sa.Column('deployment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('moderator_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('conf', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_heartbeat', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['moderator_id'], ['moderators.moderator_id'], name=op.f('moderator_deployments_moderator_id_fkey')),
    sa.PrimaryKeyConstraint('deployment_id', name=op.f('moderator_deployments_pkey'))
    )
    op.drop_index(op.f('ix_moderator_event_logs_event_type'), table_name='moderator_event_logs')
    op.drop_index(op.f('ix_moderator_event_logs_created_at'), table_name='moderator_event_logs')
    op.drop_table('moderator_event_logs')
    # ### end Alembic commands ###
