"""renamed state field to status

Revision ID: 364a10bfd7a9
Revises: ee70ed94a2a1
Create Date: 2025-10-21 09:45:14.124710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '364a10bfd7a9'
down_revision: Union[str, Sequence[str], None] = 'ee70ed94a2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderator_deployments', sa.Column('status', sa.String(), nullable=False))
    op.drop_column('moderator_deployments', 'state')
    op.add_column('moderator_logs', sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moderator_logs', 'context')
    op.add_column('moderator_deployments', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('moderator_deployments', 'status')
    # ### end Alembic commands ###
