"""removed connections field and added discord_oauth field in users

Revision ID: 3fb59576d2bd
Revises: c76e321f6631
Create Date: 2025-10-30 08:28:37.701618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fb59576d2bd'
down_revision: Union[str, Sequence[str], None] = 'c76e321f6631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('discord_oauth', sa.String(), nullable=True))
    op.drop_column('users', 'connections')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('connections', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('users', 'discord_oauth')
    # ### end Alembic commands ###
