"""Added error_msg field to action_events

Revision ID: 6cd8e388a6c5
Revises: 18b225b423ce
Create Date: 2026-01-21 11:50:39.372181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cd8e388a6c5'
down_revision: Union[str, Sequence[str], None] = '18b225b423ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_events', sa.Column('error_msg', sa.String(), nullable=True))
    op.alter_column('users', 'pricing_tier',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'pricing_tier',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('action_events', 'error_msg')
    # ### end Alembic commands ###
