"""removed server id field in moderator_deployments

Revision ID: 6e771b3131bd
Revises: 2c099994dd30
Create Date: 2025-11-01 15:28:08.040591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e771b3131bd'
down_revision: Union[str, Sequence[str], None] = '2c099994dd30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moderator_deployments', 'server_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderator_deployments', sa.Column('server_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
