"""x

Revision ID: 74b228c3ef45
Revises: aa4dff13b5cf
Create Date: 2025-10-31 12:49:33.462351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74b228c3ef45'
down_revision: Union[str, Sequence[str], None] = 'aa4dff13b5cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderator_deployment_event_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('moderator_id', sa.UUID(), nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('action_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_status', sa.String(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['moderator_deployments.deployment_id'], ),
    sa.ForeignKeyConstraint(['moderator_id'], ['moderators.moderator_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_moderator_deployment_event_logs_created_at'), 'moderator_deployment_event_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_moderator_deployment_event_logs_event_type'), 'moderator_deployment_event_logs', ['event_type'], unique=False)
    op.drop_table('moderator_logs')
    op.add_column('message_evaluations', sa.Column('violation_detected', sa.Boolean(), nullable=False))
    op.add_column('message_evaluations', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('messages', sa.Column('platform_message_id', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('platform_author_id', sa.String(), nullable=True))
    op.add_column('moderator_deployments', sa.Column('server_id', sa.String(), nullable=True))
    op.add_column('moderator_deployments', sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moderator_deployments', 'last_heartbeat')
    op.drop_column('moderator_deployments', 'server_id')
    op.drop_column('messages', 'platform_author_id')
    op.drop_column('messages', 'platform_message_id')
    op.drop_column('message_evaluations', 'confidence_score')
    op.drop_column('message_evaluations', 'violation_detected')
    op.create_table('moderator_logs',
    sa.Column('log_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('moderator_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('action_params', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('deployment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['moderator_deployments.deployment_id'], name=op.f('moderator_logs_deployment_id_fkey')),
    sa.ForeignKeyConstraint(['moderator_id'], ['moderators.moderator_id'], name=op.f('moderator_logs_moderator_id_fkey')),
    sa.PrimaryKeyConstraint('log_id', name=op.f('moderator_logs_pkey'))
    )
    op.drop_index(op.f('ix_moderator_deployment_event_logs_event_type'), table_name='moderator_deployment_event_logs')
    op.drop_index(op.f('ix_moderator_deployment_event_logs_created_at'), table_name='moderator_deployment_event_logs')
    op.drop_table('moderator_deployment_event_logs')
    # ### end Alembic commands ###
