"""removed payment_info and payment_link field sfrom users

Revision ID: 7f19894fb751
Revises: 6e771b3131bd
Create Date: 2025-11-01 17:15:24.316646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f19894fb751'
down_revision: Union[str, Sequence[str], None] = '6e771b3131bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'payment_link')
    op.drop_column('users', 'payment_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('payment_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('payment_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
