"""renamed all occurences of breach to topic

Revision ID: 8fe46c47c445
Revises: ad1b8bd09389
Create Date: 2025-10-15 22:28:53.320347

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8fe46c47c445"
down_revision: Union[str, Sequence[str], None] = "ad1b8bd09389"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "guidelines",
        sa.Column("topics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.execute("UPDATE guidelines SET topics = breach_types;")
    op.execute("ALTER TABLE guidelines ALTER COLUMN topics SET NOT NULL;")

    op.drop_column("guidelines", "breach_types")
    op.add_column("messages", sa.Column("topic", sa.String(), nullable=True))
    op.add_column("messages", sa.Column("topic_score", sa.Float(), nullable=True))
    op.execute("UPDATE messages SET topic=breach_type, topic_score=breach_score;")
    op.execute("ALTER TABLE messages ALTER COLUMN topic SET NOT NULL;")
    op.execute("ALTER TABLE messages ALTER COLUMN topic_score SET NOT NULL;")
    op.drop_column("messages", "breach_score")
    op.drop_column("messages", "breach_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column("breach_type", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "messages",
        sa.Column(
            "breach_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("messages", "topic_score")
    op.drop_column("messages", "topic")
    op.add_column(
        "guidelines",
        sa.Column(
            "breach_types",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("guidelines", "topics")
    # ### end Alembic commands ###
