"""added jwt field to users table

Revision ID: aa4dff13b5cf
Revises: 3fb59576d2bd
Create Date: 2025-10-30 11:24:52.241954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa4dff13b5cf'
down_revision: Union[str, Sequence[str], None] = '3fb59576d2bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('jwt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'jwt')
    # ### end Alembic commands ###
