"""updated

Revision ID: ad1b8bd09389
Revises: a4f75bfacf1d
Create Date: 2025-10-15 21:12:03.488065

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad1b8bd09389'
down_revision: Union[str, Sequence[str], None] = 'a4f75bfacf1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=4),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=4),
               existing_nullable=False)
    # ### end Alembic commands ###
