"""converted pricing_tier field to integer

Revision ID: de8ff82b2dfc
Revises: 808d9c255bbb
Create Date: 2025-10-25 17:41:41.443697

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de8ff82b2dfc"
down_revision: Union[str, Sequence[str], None] = "808d9c255bbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE users
        ADD COLUMN pricing_tier_tmp INTEGER DEFAULT 0;
        """
    )
    op.execute(
        """
        UPDATE users
        SET pricing_tier_tmp = 
            CASE pricing_tier
                WHEN 'free' THEN 0
                WHEN 'pro' THEN 1
                WHEN 'enterprise' THEN 2
            END
        ;
        """
    )
    op.execute(
        """
        ALTER TABLE users
        DROP COLUMN pricing_tier;
        """
    )
    op.execute(
        """
        ALTER TABLE users
        RENAME COLUMN pricing_tier_tmp TO pricing_tier;
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE users
        ADD COLUMN pricing_tier_tmp VARCHAR DEFAULT 'free';
        """
    )
    op.execute(
        """
        UPDATE users
        SET pricing_tier_tmp =
            CASE pricing_tier
                WHEN 0 THEN 'free'
                WHEN 1 THEN 'pro'
                WHEN 2 THEN 'enterprise'
            END
        ;
        """
    )
    op.execute(
        """
        ALTER TABLE users
        DROP COLUMN pricing_tier;
        """
    )
    op.execute(
        """
        ALTER TABLE users
        RENAME COLUMN pricing_tier_tmp TO pricing_tier;
        """
    )
