"""Added event_id primary key field to evaluation_events

Revision ID: ffef9c434519
Revises: d52e7fcd332d
Create Date: 2026-01-18 14:16:10.785386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffef9c434519'
down_revision: Union[str, Sequence[str], None] = 'd52e7fcd332d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
